# Generated by Django 3.1.5 on 2021-01-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Booked', 'Booked'), ('Scanned', 'Scanned'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], default='New', max_length=10)),
                ('time_of_request', models.DateTimeField()),
                ('time_of_entry', models.DateTimeField()),
                ('time_of_exit', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('email_address', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.IntegerField(primary_key=True, serialize=False)),
                ('max_customers', models.IntegerField()),
                ('current_customers', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.position')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user', to_field='email_address')),
            ],
        ),
    ]
