# Generated by Django 3.1.5 on 2021-01-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_store_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.store'),
        ),
    ]
