# Generated by Django 3.1.5 on 2021-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210129_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='managed_store_id',
        ),
        migrations.AddField(
            model_name='user',
            name='managed_store_id',
            field=models.ManyToManyField(to='api.Store'),
        ),
    ]
