# Generated by Django 3.1.5 on 2021-01-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210129_1255'),
        ('api', '0007_auto_20210130_1545'),
    ]

    operations = [
    ]
